version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3.8.22-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
  spring-app:
    image: "narang:latest"
    ports:
      - "8084:8084"
    depends_on:
      - rabbitmq

